// Copyright (C) <2018> Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0
#import "OWT/OWTStream.h"
#import "OWT/OWTMediaFormat.h"
NS_ASSUME_NONNULL_BEGIN
@protocol OWTRemoteStreamDelegate;
/// This class represents a remote stream.
RTC_OBJC_EXPORT
@interface OWTRemoteStream : OWTStream
/**
  Get the stream owner's ID.
  If will be an empty string if a stream is generated by MCU server.
*/
@property(nonatomic, strong, readonly) NSString* origin;
/**
  Get stream's ID
*/
@property(nonatomic, strong, readonly) NSString* streamId;

@property(nonatomic, strong, readonly) OWTPublicationSettings* settings;
/// Original settings for publishing this stream.
@property(nonatomic, strong, readonly) OWTSubscriptionCapabilities* capabilities;
/// Capabilities remote endpoint provides for subscription.
@property(nonatomic, weak, readwrite) id<OWTRemoteStreamDelegate> delegate;
@end
RTC_OBJC_EXPORT
@protocol OWTRemoteStreamDelegate<NSObject>
/// Triggered when a stream is ended, or the stream is no longer available in
/// conference.
- (void)streamDidEnd:(OWTRemoteStream*)stream;
/// Triggered when a stream is updated.
- (void)streamDidUpdate:(OWTRemoteStream*)stream;
/// Triggered when stream is muted.
- (void)streamDidMute:(OWTRemoteStream*)stream
                  trackKind:(OWTTrackKind)kind;
/// Triggered when stream is unmuted.
- (void)streamDidUnmute:(OWTRemoteStream*)stream
                    trackKind:(OWTTrackKind)kind;
@end
NS_ASSUME_NONNULL_END
