// Copyright (C) <2018> Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0
#import "OMS/OMSStream.h"
#import "OMS/OMSMediaFormat.h"
NS_ASSUME_NONNULL_BEGIN
@protocol OMSRemoteStreamDelegate;
/// This class represents a remote stream.
RTC_EXPORT
@interface OMSRemoteStream : OMSStream
/**
  Get the stream owner's ID.
  If will be an empty string if a stream is generated by MCU server.
*/
@property(nonatomic, strong, readonly) NSString* origin;
/**
  Get stream's ID
*/
@property(nonatomic, strong, readonly) NSString* streamId;

@property(nonatomic, strong, readonly) OMSPublicationSettings* settings;
/// Original settings for publishing this stream.
@property(nonatomic, strong, readonly) OMSSubscriptionCapabilities* capabilities;
/// Capabilities remote endpoint provides for subscription.
@property(nonatomic, weak, readwrite) id<OMSRemoteStreamDelegate> delegate;
@end
RTC_EXPORT
@protocol OMSRemoteStreamDelegate<NSObject>
/// Triggered when a stream is ended, or the stream is no longer available in
/// conference.
- (void)streamDidEnd:(OMSRemoteStream*)stream;
/// Triggered when a stream is updated.
- (void)streamDidUpdate:(OMSRemoteStream*)stream;
@end
NS_ASSUME_NONNULL_END
